#!/bin/bash

echo "📝 Atualizando descrição do repositório no GitHub..."
echo ""
echo "Para atualizar a descrição do repositório no GitHub, você tem 2 opções:"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "OPÇÃO 1: Via linha de comando (GitHub CLI)"
echo "-------------------------------------------"
echo "Execute este comando:"
echo ""
echo 'gh repo edit decomontenegro/CulturaBuilder-MCP --description "MCP para Claude Desktop com comandos especializados de desenvolvimento | Fork adaptado para a comunidade CulturaBuilder"'
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "OPÇÃO 2: Via interface web do GitHub"
echo "-------------------------------------"
echo "1. Acesse: https://github.com/decomontenegro/CulturaBuilder-MCP"
echo "2. Clique no ícone de engrenagem ⚙️ ao lado de 'About'"
echo "3. No campo 'Description', remova 'CulturaBuilder v3 🚀'"
echo "4. Substitua por: 'MCP para Claude Desktop com comandos especializados de desenvolvimento'"
echo "5. Clique em 'Save changes'"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "💡 DICA: A descrição aparece:"
echo "   - No topo do repositório (abaixo do nome)"
echo "   - Na seção 'About' do lado direito"
echo "   - Nos resultados de busca do GitHub"
echo ""
echo "✅ Após atualizar, o repositório mostrará apenas a arte ASCII no README!"